const fs = require('fs');
const path = require('path');

const files = {
  '__tests__/dashboard/containerList.test.tsx': `import { render, screen } from '@testing-library/react';\nimport ContainerList from '@/components/dashboard/ContainerList';\n\ndescribe('ContainerList', () => {\n  it('renders a list of containers', () => {\n    const mockContainers = [\n      { id: '1', name: 'nginx-proxy', image: 'nginx:latest', status: 'running' },\n      { id: '2', name: 'db-mysql', image: 'mysql:8', status: 'stopped' },\n    ];\n    render(<ContainerList containers={mockContainers} />);\n    expect(screen.getByText('nginx-proxy')).toBeInTheDocument();\n    expect(screen.getByText('db-mysql')).toBeInTheDocument();\n  });\n});`,
  
  '__tests__/dashboard/statusIndicators.test.tsx': `import { render, screen } from '@testing-library/react';\nimport StatusIndicator from '@/components/dashboard/StatusIndicator';\n\ndescribe('StatusIndicator', () => {\n  it('renders green for running status', () => {\n    render(<StatusIndicator status="running" />);\n    const indicator = screen.getByTestId('status-indicator');\n    expect(indicator).toHaveClass('bg-green-500');\n  });\n  it('renders red for stopped status', () => {\n    render(<StatusIndicator status="stopped" />);\n    const indicator = screen.getByTestId('status-indicator');\n    expect(indicator).toHaveClass('bg-red-500');\n  });\n});`,

  '__tests__/containers/actions.test.tsx': `import { render, screen, fireEvent } from '@testing-library/react';\nimport ActionButtons from '@/components/containers/ActionButtons';\n\ndescribe('ActionButtons', () => {\n  it('calls start action when clicking start', () => {\n    const onStart = jest.fn();\n    render(<ActionButtons status="stopped" onStart={onStart} onStop={jest.fn()} onDelete={jest.fn()} />);\n    fireEvent.click(screen.getByRole('button', { name: /démarrer/i }));\n    expect(onStart).toHaveBeenCalled();\n  });\n});`,

  '__tests__/containers/creationForm.test.tsx': `import { render, screen } from '@testing-library/react';\nimport CreationForm from '@/components/containers/CreationForm';\n\ndescribe('CreationForm', () => {\n  it('renders required inputs for creation', () => {\n    render(<CreationForm onSubmit={jest.fn()} />);\n    expect(screen.getByLabelText(/nom du container/i)).toBeInTheDocument();\n    expect(screen.getByLabelText(/image docker/i)).toBeInTheDocument();\n    expect(screen.getByRole('button', { name: /déployer/i })).toBeInTheDocument();\n  });\n});`,

  '__tests__/monitoring/logs.test.tsx': `import { render, screen } from '@testing-library/react';\nimport LogsModal from '@/components/monitoring/LogsModal';\n\ndescribe('LogsModal', () => {\n  it('displays logs correctly', () => {\n    const mockLogs = "Starting NGINX...\\nReady.";\n    render(<LogsModal isOpen={true} onClose={jest.fn()} logs={mockLogs} />);\n    expect(screen.getByText(/Starting NGINX.../i)).toBeInTheDocument();\n  });\n});`,

  '__tests__/images/searchPull.test.tsx': `import { render, screen } from '@testing-library/react';\nimport SearchBar from '@/components/images/SearchBar';\n\ndescribe('SearchBar', () => {\n  it('allows user to search an image', () => {\n    render(<SearchBar onSearch={jest.fn()} />);\n    expect(screen.getByPlaceholderText(/rechercher une image/i)).toBeInTheDocument();\n    expect(screen.getByRole('button', { name: /chercher/i })).toBeInTheDocument();\n  });\n});`,

  'src/components/dashboard/StatusIndicator.tsx': `export default function StatusIndicator({ status }: { status: 'running' | 'stopped' }) {\n  const isRunning = status === 'running';\n  return (\n    <span className="flex items-center space-x-2">\n      <span \n        data-testid="status-indicator" \n        className={\`w-3 h-3 rounded-full shadow-[0_0_8px_rgba(0,0,0,0.5)] \${isRunning ? 'bg-green-500 shadow-green-500/50' : 'bg-red-500 shadow-red-500/50'}\`}\n      ></span>\n      <span className="text-sm text-slate-300 capitalize">{status}</span>\n    </span>\n  );\n}`,

  'src/components/containers/ActionButtons.tsx': `export default function ActionButtons({ status, onStart, onStop, onDelete }: any) {\n  const isRunning = status === 'running';\n  return (\n    <div className="flex space-x-2">\n      {!isRunning && (\n        <button onClick={onStart} className="px-3 py-1 bg-green-500/20 text-green-400 hover:bg-green-500/30 rounded-lg text-sm font-semibold transition-all">Démarrer</button>\n      )}\n      {isRunning && (\n        <button onClick={onStop} className="px-3 py-1 bg-amber-500/20 text-amber-400 hover:bg-amber-500/30 rounded-lg text-sm font-semibold transition-all">Arrêter</button>\n      )}\n      <button onClick={onDelete} className="px-3 py-1 bg-red-500/20 text-red-400 hover:bg-red-500/30 rounded-lg text-sm font-semibold transition-all">Supprimer</button>\n    </div>\n  );\n}`,

  'src/components/dashboard/ContainerList.tsx': `import StatusIndicator from './StatusIndicator';\nimport ActionButtons from '../containers/ActionButtons';\n\nexport default function ContainerList({ containers }: { containers: any[] }) {\n  if (containers.length === 0) {\n    return <div className="p-8 text-center text-slate-400 bg-white/5 rounded-2xl border border-white/10">Aucun container trouvé.</div>;\n  }\n  return (\n    <div className="space-y-4">\n      {containers.map(c => (\n        <div key={c.id} className="flex items-center justify-between p-4 bg-white/5 hover:bg-white/10 border border-white/10 rounded-2xl transition-all backdrop-blur-sm">\n          <div>\n            <h3 className="text-lg font-bold text-white">{c.name}</h3>\n            <p className="text-sm text-slate-400">{c.image}</p>\n          </div>\n          <div className="flex items-center space-x-6">\n            <StatusIndicator status={c.status} />\n            <ActionButtons status={c.status} onStart={() => {}} onStop={() => {}} onDelete={() => {}} />\n          </div>\n        </div>\n      ))}\n    </div>\n  );\n}`,

  'src/components/containers/CreationForm.tsx': `export default function CreationForm({ onSubmit }: { onSubmit: (data: any) => void }) {\n  return (\n    <form onSubmit={(e) => { e.preventDefault(); onSubmit({}); }} className="p-6 bg-white/5 border border-white/10 rounded-2xl space-y-4 backdrop-blur-md">\n      <h3 className="text-xl font-bold text-white mb-4">Nouveau Container</h3>\n      <div>\n        <label htmlFor="name" className="block text-sm text-slate-300">Nom du container</label>\n        <input id="name" required className="mt-1 w-full bg-black/20 border border-white/10 rounded-xl px-4 py-2 text-white focus:ring-2 focus:ring-purple-500 outline-none" />\n      </div>\n      <div>\n        <label htmlFor="image" className="block text-sm text-slate-300">Image Docker</label>\n        <input id="image" required className="mt-1 w-full bg-black/20 border border-white/10 rounded-xl px-4 py-2 text-white focus:ring-2 focus:ring-purple-500 outline-none" />\n      </div>\n      <button type="submit" className="w-full mt-4 py-2 bg-gradient-to-r from-blue-600 to-indigo-600 rounded-xl font-bold text-white hover:from-blue-500 hover:to-indigo-500 transition-all shadow-lg">Déployer</button>\n    </form>\n  );\n}`,

  'src/components/monitoring/LogsModal.tsx': `export default function LogsModal({ isOpen, onClose, logs }: { isOpen: boolean, onClose: () => void, logs: string }) {\n  if (!isOpen) return null;\n  return (\n    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">\n      <div className="bg-[#0f172a] border border-white/10 rounded-2xl w-full max-w-3xl overflow-hidden shadow-2xl">\n        <div className="flex justify-between items-center p-4 border-b border-white/10 bg-white/5">\n          <h3 className="text-white font-bold">Logs du container</h3>\n          <button onClick={onClose} className="text-slate-400 hover:text-white font-bold">X</button>\n        </div>\n        <div className="p-4 bg-black/50 h-96 overflow-y-auto">\n          <pre className="text-green-400 font-mono text-sm whitespace-pre-wrap">{logs}</pre>\n        </div>\n      </div>\n    </div>\n  );\n}`,

  'src/components/images/SearchBar.tsx': `export default function SearchBar({ onSearch }: { onSearch: (q: string) => void }) {\n  return (\n    <div className="flex space-x-2">\n      <input placeholder="Rechercher une image..." className="flex-1 bg-white/5 border border-white/10 rounded-xl px-4 py-2 text-white focus:ring-2 focus:ring-indigo-500 outline-none" />\n      <button onClick={() => onSearch('test')} className="px-6 py-2 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-xl transition-all shadow-lg">Chercher</button>\n    </div>\n  );\n}`,

  'src/app/dashboard/page.tsx': `import ContainerList from '@/components/dashboard/ContainerList';\nimport CreationForm from '@/components/containers/CreationForm';\nimport SearchBar from '@/components/images/SearchBar';\n\nexport default function DashboardPage() {\n  const mockContainers = [\n    { id: '1', name: 'nginx-proxy', image: 'nginx:latest', status: 'running' },\n    { id: '2', name: 'db-mysql', image: 'mysql:8', status: 'stopped' }\n  ];\n\n  return (\n    <div className="min-h-screen bg-[#0f172a] text-white p-8 relative overflow-hidden">\n      {/* Background decoration */}\n      <div className="absolute top-[-10%] right-[-10%] w-96 h-96 bg-purple-600 rounded-full mix-blend-screen filter blur-[128px] opacity-20"></div>\n      \n      <div className="max-w-6xl mx-auto relative z-10 space-y-8">\n        <header className="flex justify-between items-center">\n          <div>\n            <h1 className="text-4xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 to-purple-400">Tableau de Bord</h1>\n            <p className="text-slate-400 mt-2">Gérez vos containers locaux</p>\n          </div>\n          <div className="w-96">\n            <SearchBar onSearch={(q) => console.log(q)} />\n          </div>\n        </header>\n\n        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">\n          <div className="lg:col-span-2 space-y-6">\n            <h2 className="text-xl font-bold text-white">Vos Containers</h2>\n            <ContainerList containers={mockContainers} />\n          </div>\n          <div>\n             <CreationForm onSubmit={() => {}} />\n          </div>\n        </div>\n      </div>\n    </div>\n  );\n}`
};

for (const [relPath, content] of Object.entries(files)) {
  const fullPath = path.join(__dirname, relPath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content);
}
console.log('All frontend files written successfully!');
